#################################################################################
# Catcher Parameters
#################################################################################

env_name: Pendulum-v0
lr: 0.0001
batch_size: 128
exp_name: SAC_continous_1
model_type: SAC
task_name: Pendulum-v0
test_task_name: Pendulum-v0
seed: 1
alpha: 0.005
change_every: 25000
buffer_size: 100.0
update_after: 200
load_model: False
visualize: False
option_dim: 2
