#################################################################################
# Catcher Parameters
#################################################################################

env_name: Rooms
lr: 0.001
batch_size: 100
exp_name: SAC_discrete_1
model_type: SAC
task_name: Rooms
test_task_name: Rooms
seed: 1
alpha: 0.05
buffer_size: 1000000
update_after: 1000
eps_decay: 5000
load_model: False
visualize: False
option_dim: 4
option_num: 4