#################################################################################
# Catcher Parameters
#################################################################################

env_name: MovementBandits-v0
lr: 0.001
batch_size: 100
exp_name: SOC_bandit_1
model_type: SOC
task_name: MovementBandits-v0
test_task_name: MovementBandits-v0
seed: 1
alpha: 0.05
eps_min: 0.0
buffer_size: 1000000
update_after: 1000
eps_decay: 1
load_model: False
visualize: False
option_num: 2
num_tasks: 2
