#################################################################################
# OPTION ALGORITHM
#################################################################################
# Starting value for epsilon-greedy exploration
eps_max: 1.0

# Ending value for epsilon-greedy exploration
eps_min: 0.15

# Number of steps to minimum epsilon
eps_decay: 50000

# Number of options for intra-option & beta policy
option_num: 2
