#################################################################################
# Catcher Parameters
#################################################################################

env_name: MyTaxi-v1
lr: 0.001
batch_size: 100
exp_name: SAC_taxi_1
model_type: SAC
task_name: MyTaxi-v1
test_task_name: MyTaxi-v1
seed: 1
alpha: 0.05
eps_min: 0.0
buffer_size: 1000000
update_after: 1000
eps_decay: 1
load_model: False
visualize: False
option_dim: 1
option_num: 1

num_tasks: 12
num_processes_per_task: 16