#################################################################################
# Catcher Parameters
#################################################################################

env_name: Taxi
lr: 0.001
batch_size: 100
exp_name: SAC_taxi_1
model_type: SAC
task_name: Taxi
test_task_name: Taxi
seed: 1
alpha: 0.05
eps_min: 0.0
change_every: 25000
buffer_size: 100.0
update_after: 1000
eps_decay: 1
load_model: False
visualize: False
option_dim: 1
option_num: 1